### PR TITLE
Only show imports from direct dependencies and separate test dependencies

### LINKED ISSUE #49: Separate tests from normal imports/forest
At the moment features like completions etc will make it seem like they work if you import the correct things, even if that is from the testing dependencies or vice versa.

### PR DESCRIPTION
**Pull request by jmbockhorst**
Fixes #49.

### CODE REVIEW

**Comment by jmbockhorst** [comment]
Currently `testModuleToUriMap` contains everything in `moduleToUriMap`. I did this for simplicity, but this seems like a big waste of memory. I will be looking into a better solution.

**Comment by jmbockhorst** [comment]
This should be ready now.

**Review by Razzeee — CHANGES_REQUESTED** [review]
Looks good, would like some tests, but I guess that might be hard, due to our tests not having an elm.json

**Review by Razzeee — APPROVED** [review]

**Comment by jmbockhorst** [comment]
I was thinking about that. In sourceTreeParser we define the elm.json for tests. And we could define sources in that test directory. I should be able to get something basic.

**Comment by Razzeee** [comment]
> I was thinking about that. In sourceTreeParser we define the elm.json for tests. And we could define sources in that test directory. I should be able to get something basic.

Yeah, something basic would be good, don't think there is much value in testing more then if we're loading the right deps (and not too much)

**Pull request merged**
