### PR TITLE
Update packages ranking

### PR DESCRIPTION
**Pull request by rlefevre**

### CODE REVIEW

**Comment by rlefevre** [comment]
Wait before merging, I think broken packages like `Skinney` ones should be removed first.

**Comment by rlefevre** [comment]
I have removed `Skinney/*` and `chelovek0v/bbase64` broken packages. I will make a script to get the full list in a future update but this should be an acceptable update already.

**Comment by rlefevre** [comment]
All broken authors and packages have been removed.

**Comment by Razzeee** [comment]
Thank you!

**Pull request merged**
