### PR TITLE
Release instructions: Nix upstream

### PR DESCRIPTION
**Pull request by andys8**
Added nix, so it won't be forgotten and left behind

### CODE REVIEW

**Comment by Razzeee** [comment]
Not sure if that "burden" should be placed here.

But basically we need to checkout the repo run https://github.com/turboMaCk/nixpkgs/blob/98997bb48997b27287a2995460d2fb6e1db88de7/pkgs/development/compilers/elm/packages/generate-node-packages.sh and push that up again?

**Comment by andys8** [comment]
That should be how it's done.

I saw this ["Upgrade downstream projects"](https://scalameta.org/metals/docs/contributors/releasing.html) in the `scala/metals` project and thought it was a good idea. We can also add "Make sure that..." in front of it.

**Comment by Razzeee** [comment]
We can try, I guess I'll get back to you after the next release :P

**Comment by andys8** [comment]
We'll figure it out ^^

**Pull request merged**
