### PR TITLE
Github Actions: test commits

### PR DESCRIPTION
**Pull request by andys8**
Trying out github actions. This workflow does the same as travis.

### CODE REVIEW

**Comment by andys8** [comment]
image

**Comment by Razzeee** [comment]
Should be working now

**Comment by andys8** [comment]
The changes probably need to be merged to take affect. May cause additional changes if not working as expected.

**Comment by andys8** [comment]
Looking good. https://github.com/elm-tooling/elm-language-server/commit/b4635f81aee6860e4a3f26c1b2a67aa14492036e/checks?check_suite_id=266294316

**Pull request merged**
