### PR TITLE
Add support for fixing all elm-analyse issues in a file

### PR DESCRIPTION
**Pull request by antew**
To go along with https://github.com/elm-tooling/elm-analyse/pull/6

fix-example

### CODE REVIEW

**Comment by Razzeee** [comment]
This is WIP due to https://github.com/elm-tooling/elm-analyse/pull/6 not being merged or anything else?

**Comment by antew** [comment]
It was WIP due to the elm-analyse piece, it should be good to go once I update it to point to the jew elm-analyse version.

**Comment by antew** [comment]
Added a PR over on the elm-analyse fork with the built files https://github.com/elm-tooling/elm-analyse/pull/7

It feels weird how elm-analyse has the built files in master, maybe we should create branches off of master, build the files there, and tag those branches instead?

**Comment by Razzeee** [comment]
Hrm, I'm fine for the moment with how it is. The upstream repo does it the same way.

**Pull request merged**
