### PR TITLE
Bugfix #89 elm test compiles tests only

### PR DESCRIPTION
**Pull request by andys8**
This PR will add working linting in tests and *not* run the tests, instead compile them only.

### CODE REVIEW

**Comment by Razzeee** [comment]
Don't we want both? And as far as I could tell, the old test code did not work. So it might be better to redo it from scratch.

**Comment by andys8** [comment]
A test can take 10 seconds and much more. I think executing test suites is a completely different feature than linting and the integration and diffing because of the performance impact is not easy at all. It can't just be randomly triggered.

**Comment by andys8** [comment]
Updated package-lock because that seems to be the issue with CI.

**Comment by andys8** [comment]
> And as far as I could tell, the old test code did not work. So it might be better to redo it from scratch.

**Comment by Razzeee** [comment]
I reworked it in master and I'm getting make, tests and diagnostics with that in vscode.

**Comment by Razzeee** [comment]
And yes, tests might be better as a command, haven't really looked into that api yet.

**Comment by andys8** [comment]
I tested the changes made to master, and it seems like the issues were addressed. It's really looking good now :) Only `package-lock.json` has to be updated (CI is failing too).

**Pull request closed without merging**
