### PR TITLE
[Bugfix] execa stripping new lines resulted wrong elm-format diff

### PR DESCRIPTION
**Pull request by andys8**
* Changing the last line duplicated the last line
* Changing the first line duplicated the whole file

<https://github.com/sindresorhus/execa#stripfinalnewline>

vokoscreen-2019-08-29_21-04-06

### CODE REVIEW

**Comment by Razzeee** [comment]
Can you make this configurable and only use it on elm make? As it's handy for the `elm --version` call

**Comment by andys8** [comment]
Or explicit `trim()` in that case?

**Comment by Razzeee** [comment]
Yes, if you want to. But please look at the git changes and just get it back from there, as it was like that before execa.

**Comment by andys8** [comment]
Okay, thanks.

You're referring to 

```
  const version = result.stdout
    .substring(0, result.stdout.indexOf("\n"))
    .trim();
```

But I would think `.trim()` should be enough.

```

**Comment by andys8** [comment]
Tested. Log says: `"message": "Elm version 0.19.0 detected."`

**Comment by Razzeee** [comment]
Tested 
Manjaro with 0.19.0 and 0.19.1-beta-1
Windows with 0.19.0

Seems to work fine, no idea why I thought that substring was necessary.

**Pull request merged**
